services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8090:8090"
    volumes:
      - ./application.properties:/app/application.properties
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME:  ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update 
      SPRING_LIQUIBASE_ENABLED: true 
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./custom-postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
