services:
  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod 
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nastya2001
      POSTGRES_DB: walletdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
